trigger: none

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node 16.x'
  inputs:
    versionSpec: 16.x

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test'