apiVersion: v1
kind: Namespace
metadata:
  name: api-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: api-backend
          image: d3p3g1registrydev.azurecr.io/di3p3g1-backend:${{ github.sha }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '256m'
              memory: '11400Mi'

---
apiVersion: v1
kind: Service
metadata:
  name: api-backend
  namespace: api-backend
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: api-backend
